// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Project struct {
	ID          int64
	UserID      int64
	Project     string
	Description sql.NullString
	Status      sql.NullString
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash string
	CreatedAt string
	ExpiresAt string
}

type Task struct {
	ID          int64
	UserID      int64
	ProjectID   int64
	Task        string
	Description sql.NullString
	Status      string
	Priority    sql.NullInt64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}
