// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteProjects = `-- name: DeleteProjects :many
DELETE FROM projects WHERE id IN (/*SLICE:ids*/?) RETURNING id, user_id, project, description, status
`

func (q *Queries) DeleteProjects(ctx context.Context, ids []int64) ([]Project, error) {
	query := deleteProjects
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Project,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProjectsByUserAndProject = `-- name: InsertProjectsByUserAndProject :one
INSERT INTO projects (user_id, project, description, status) VALUES (?, ?, ?, ?) RETURNING id, user_id, project, description, status
`

type InsertProjectsByUserAndProjectParams struct {
	UserID      int64
	Project     string
	Description sql.NullString
	Status      string
}

func (q *Queries) InsertProjectsByUserAndProject(ctx context.Context, arg InsertProjectsByUserAndProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProjectsByUserAndProject,
		arg.UserID,
		arg.Project,
		arg.Description,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Project,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const selectProjectsByUserAndProject = `-- name: SelectProjectsByUserAndProject :many
SELECT id, user_id, project, description, status FROM projects WHERE user_id = ?
`

func (q *Queries) SelectProjectsByUserAndProject(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, selectProjectsByUserAndProject, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Project,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectProjectsByUserAndProjectId = `-- name: SelectProjectsByUserAndProjectId :one
SELECT id, user_id, project, description, status FROM projects WHERE user_id = ? AND id = ?
`

type SelectProjectsByUserAndProjectIdParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) SelectProjectsByUserAndProjectId(ctx context.Context, arg SelectProjectsByUserAndProjectIdParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, selectProjectsByUserAndProjectId, arg.UserID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Project,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const updateProjectsByUserAndProject = `-- name: UpdateProjectsByUserAndProject :exec
UPDATE projects SET project = ?, description = ?, status = ? WHERE id = ? AND user_id = ?
`

type UpdateProjectsByUserAndProjectParams struct {
	Project     string
	Description sql.NullString
	Status      string
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateProjectsByUserAndProject(ctx context.Context, arg UpdateProjectsByUserAndProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectsByUserAndProject,
		arg.Project,
		arg.Description,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}
