// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sub_project_queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSubProjects = `-- name: DeleteSubProjects :one
DELETE FROM sub_projects WHERE user_id = ? AND id = ? AND project_id = ? RETURNING id, user_id, project_id, sub_project, description, status
`

type DeleteSubProjectsParams struct {
	UserID    int64
	ID        int64
	ProjectID int64
}

func (q *Queries) DeleteSubProjects(ctx context.Context, arg DeleteSubProjectsParams) (SubProject, error) {
	row := q.db.QueryRowContext(ctx, deleteSubProjects, arg.UserID, arg.ID, arg.ProjectID)
	var i SubProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SubProject,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const insertSubProject = `-- name: InsertSubProject :one
INSERT INTO sub_projects (user_id, project_id, sub_project, description, status) VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, project_id, sub_project, description, status
`

type InsertSubProjectParams struct {
	UserID      int64
	ProjectID   int64
	SubProject  string
	Description sql.NullString
	Status      string
}

func (q *Queries) InsertSubProject(ctx context.Context, arg InsertSubProjectParams) (SubProject, error) {
	row := q.db.QueryRowContext(ctx, insertSubProject,
		arg.UserID,
		arg.ProjectID,
		arg.SubProject,
		arg.Description,
		arg.Status,
	)
	var i SubProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SubProject,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const selectSubProjectIdBySubProjectName = `-- name: SelectSubProjectIdBySubProjectName :one
SELECT id FROM sub_projects WHERE sub_project = ? AND user_id = ? AND project_id = ?
`

type SelectSubProjectIdBySubProjectNameParams struct {
	SubProject string
	UserID     int64
	ProjectID  int64
}

func (q *Queries) SelectSubProjectIdBySubProjectName(ctx context.Context, arg SelectSubProjectIdBySubProjectNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectSubProjectIdBySubProjectName, arg.SubProject, arg.UserID, arg.ProjectID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const selectSubProjectsByUserAndProject = `-- name: SelectSubProjectsByUserAndProject :many
SELECT id, user_id, project_id, sub_project, description, status FROM sub_projects WHERE user_id = ? and project_id = ? ORDER BY sub_project
`

type SelectSubProjectsByUserAndProjectParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) SelectSubProjectsByUserAndProject(ctx context.Context, arg SelectSubProjectsByUserAndProjectParams) ([]SubProject, error) {
	rows, err := q.db.QueryContext(ctx, selectSubProjectsByUserAndProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubProject
	for rows.Next() {
		var i SubProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.SubProject,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubProjectsByUserAndProject = `-- name: UpdateSubProjectsByUserAndProject :exec
UPDATE sub_projects SET sub_project = ?, description = ?, status = ? WHERE id = ? AND user_id = ? AND project_id = ?
`

type UpdateSubProjectsByUserAndProjectParams struct {
	SubProject  string
	Description sql.NullString
	Status      string
	ID          int64
	UserID      int64
	ProjectID   int64
}

func (q *Queries) UpdateSubProjectsByUserAndProject(ctx context.Context, arg UpdateSubProjectsByUserAndProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateSubProjectsByUserAndProject,
		arg.SubProject,
		arg.Description,
		arg.Status,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
	)
	return err
}
