// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks_queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteTask = `-- name: DeleteTask :many
DELETE FROM tasks WHERE id IN (/*SLICE:ids*/?) RETURNING id, user_id, project_id, task, description, status, priority
`

func (q *Queries) DeleteTask(ctx context.Context, ids []int64) ([]Task, error) {
	query := deleteTask
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Task,
			&i.Description,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTasksByUserAndProject = `-- name: InsertTasksByUserAndProject :one
INSERT INTO tasks (task, description, status, priority) VALUES (?, ?, ?, ?) RETURNING id, user_id, project_id, task, description, status, priority
`

type InsertTasksByUserAndProjectParams struct {
	Task        string
	Description sql.NullString
	Status      string
	Priority    sql.NullInt64
}

func (q *Queries) InsertTasksByUserAndProject(ctx context.Context, arg InsertTasksByUserAndProjectParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, insertTasksByUserAndProject,
		arg.Task,
		arg.Description,
		arg.Status,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Task,
		&i.Description,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const selectTasksByUserAndProject = `-- name: SelectTasksByUserAndProject :many
SELECT id, user_id, project_id, task, description, status, priority FROM tasks WHERE user_id = ? AND project_id = ?
`

type SelectTasksByUserAndProjectParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) SelectTasksByUserAndProject(ctx context.Context, arg SelectTasksByUserAndProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, selectTasksByUserAndProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Task,
			&i.Description,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTasksByUserAndProject = `-- name: UpdateTasksByUserAndProject :exec
UPDATE tasks SET task = ?, description = ?, status = ?, priority = ? WHERE id = ? AND user_id = ?
`

type UpdateTasksByUserAndProjectParams struct {
	Task        string
	Description sql.NullString
	Status      string
	Priority    sql.NullInt64
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateTasksByUserAndProject(ctx context.Context, arg UpdateTasksByUserAndProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateTasksByUserAndProject,
		arg.Task,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ID,
		arg.UserID,
	)
	return err
}
