// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks_queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteTask = `-- name: DeleteTask :many
DELETE FROM tasks WHERE id IN (/*SLICE:ids*/?) RETURNING id, user_id, project_id, sub_project_id, task, description, status, priority
`

func (q *Queries) DeleteTask(ctx context.Context, ids []int64) ([]Task, error) {
	query := deleteTask
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.SubProjectID,
			&i.Task,
			&i.Description,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTasksByUserAndProject = `-- name: InsertTasksByUserAndProject :one
INSERT INTO tasks (user_id, sub_project_id, project_id, task, description, status, priority) VALUES (?, NULL, ?, ?, ?, ?, ?) RETURNING id, user_id, project_id, sub_project_id, task, description, status, priority
`

type InsertTasksByUserAndProjectParams struct {
	UserID      int64
	ProjectID   int64
	Task        string
	Description sql.NullString
	Status      string
	Priority    string
}

func (q *Queries) InsertTasksByUserAndProject(ctx context.Context, arg InsertTasksByUserAndProjectParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, insertTasksByUserAndProject,
		arg.UserID,
		arg.ProjectID,
		arg.Task,
		arg.Description,
		arg.Status,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SubProjectID,
		&i.Task,
		&i.Description,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const insertTasksByUserProjectAndSubProject = `-- name: InsertTasksByUserProjectAndSubProject :one
INSERT INTO tasks (user_id, sub_project_id, project_id, task, description, status, priority) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, project_id, sub_project_id, task, description, status, priority
`

type InsertTasksByUserProjectAndSubProjectParams struct {
	UserID       int64
	SubProjectID interface{}
	ProjectID    int64
	Task         string
	Description  sql.NullString
	Status       string
	Priority     string
}

func (q *Queries) InsertTasksByUserProjectAndSubProject(ctx context.Context, arg InsertTasksByUserProjectAndSubProjectParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, insertTasksByUserProjectAndSubProject,
		arg.UserID,
		arg.SubProjectID,
		arg.ProjectID,
		arg.Task,
		arg.Description,
		arg.Status,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SubProjectID,
		&i.Task,
		&i.Description,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const selectTasksByUserAndProject = `-- name: SelectTasksByUserAndProject :many
SELECT
    tasks.id,
    tasks.task,
    tasks.description,
    tasks.status,
    tasks.priority,
    tasks.project_id,
    tasks.sub_project_id,
    sub_projects.sub_project
FROM tasks
LEFT JOIN sub_projects
    ON sub_projects.id = tasks.sub_project_id
   AND sub_projects.user_id = tasks.user_id
   AND sub_projects.project_id = tasks.project_id
WHERE tasks.user_id = ?
  AND tasks.project_id = ?
ORDER BY tasks.id DESC
`

type SelectTasksByUserAndProjectParams struct {
	UserID    int64
	ProjectID int64
}

type SelectTasksByUserAndProjectRow struct {
	ID           int64
	Task         string
	Description  sql.NullString
	Status       string
	Priority     string
	ProjectID    int64
	SubProjectID interface{}
	SubProject   sql.NullString
}

func (q *Queries) SelectTasksByUserAndProject(ctx context.Context, arg SelectTasksByUserAndProjectParams) ([]SelectTasksByUserAndProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, selectTasksByUserAndProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTasksByUserAndProjectRow
	for rows.Next() {
		var i SelectTasksByUserAndProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ProjectID,
			&i.SubProjectID,
			&i.SubProject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTasksByUserAndProjectAndSubProject = `-- name: SelectTasksByUserAndProjectAndSubProject :many
SELECT
    tasks.id,
    tasks.task,
    tasks.description,
    tasks.status,
    tasks.priority,
    tasks.project_id,
    tasks.sub_project_id,
    sub_projects.sub_project
FROM tasks
LEFT JOIN sub_projects
    ON sub_projects.id = tasks.sub_project_id
   AND sub_projects.user_id = tasks.user_id
   AND sub_projects.project_id = tasks.project_id
WHERE tasks.user_id = ?
  AND tasks.project_id = ?
  AND tasks.sub_project_id = ?
ORDER BY tasks.id DESC
`

type SelectTasksByUserAndProjectAndSubProjectParams struct {
	UserID       int64
	ProjectID    int64
	SubProjectID interface{}
}

type SelectTasksByUserAndProjectAndSubProjectRow struct {
	ID           int64
	Task         string
	Description  sql.NullString
	Status       string
	Priority     string
	ProjectID    int64
	SubProjectID interface{}
	SubProject   sql.NullString
}

func (q *Queries) SelectTasksByUserAndProjectAndSubProject(ctx context.Context, arg SelectTasksByUserAndProjectAndSubProjectParams) ([]SelectTasksByUserAndProjectAndSubProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, selectTasksByUserAndProjectAndSubProject, arg.UserID, arg.ProjectID, arg.SubProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTasksByUserAndProjectAndSubProjectRow
	for rows.Next() {
		var i SelectTasksByUserAndProjectAndSubProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ProjectID,
			&i.SubProjectID,
			&i.SubProject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTasksByUserAndProject = `-- name: UpdateTasksByUserAndProject :exec
UPDATE tasks SET task = ?, description = ?, status = ?, priority = ? WHERE id = ? AND user_id = ?
`

type UpdateTasksByUserAndProjectParams struct {
	Task        string
	Description sql.NullString
	Status      string
	Priority    string
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateTasksByUserAndProject(ctx context.Context, arg UpdateTasksByUserAndProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateTasksByUserAndProject,
		arg.Task,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ID,
		arg.UserID,
	)
	return err
}
