// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, password_hash) VALUES (?,?) RETURNING id, username, password_hash, created_at, updated_at
`

type InsertUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByUsername = `-- name: SelectUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) SelectUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
